// CONFIG REDUCER
export const INIT_LOAD = 'INIT_LOAD';
export const INIT_FINISH = 'INIT_FINISH';
export const GET_CONFIG = 'GET_CONFIG';
export const GET_GENRES = 'GET_GENRES';
export const MENU_SELECT = 'MENU_SELECT';
export const REMOVE_MENU_SELECT = 'REMOVE_MENU_SELECT';

// MOVIES REDUCER
export const FETCH_MOVIES_EXPLORE = 'FETCH_MOVIES_EXPLORE';
export const FETCH_MOVIES_GENRE = 'FETCH_MOVIES_GENRE';
export const FETCH_MOVIES_SEARCH = 'FETCH_MOVIES_SEARCH';
export const FETCH_MOVIES_LOAD = 'FETCH_MOVIES_LOAD';
export const FETCH_MOVIES_FINISH = 'FETCH_MOVIES_FINISH';

// MOVIE REDUCER
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_CAST = 'FETCH_CAST';
export const FETCH_MOVIE_LOAD = 'FETCH_MOVIE_LOAD';
export const FETCH_MOVIE_FINISH = 'FETCH_MOVIE_FINISH';

// ACTOR REDUCER
export const FETCH_ACTOR = 'FETCH_ACTOR';
export const FETCH_ACTOR_LOAD = 'FETCH_ACTOR_LOAD';
export const FETCH_ACTOR_FINISH = 'FETCH_ACTOR_FINISH';

// ACTOR MOVIES REDUCER
export const FETCH_ACTOR_MOVIES = 'FETCH_ACTOR_MOVIES';
export const FETCH_ACTOR_MOVIES_LOAD = 'FETCH_ACTOR_MOVIES_LOAD';
export const FETCH_ACTOR_MOVIES_FINISH = 'FETCH_ACTOR_MOVIES_FINISH';

// RECOMMENDED REDUCER
export const FETCH_RECOMMENDED = 'FETCH_RECOMMENDED';
export const FETCH_RECOMMENDED_LOAD = 'FETCH_RECOMMENDED_LOAD';
export const FETCH_RECOMMENDED_FINISH = 'FETCH_RECOMMENDED_FINISH';

// ERROR REDUCER
export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
